services:
  - type: web
    name: bronxbot-web
    env: python
    buildCommand: pip install -r requirements.web.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: MONGO_URI
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_OWNER_ID
        sync: false
    healthCheckPath: /debug
    autoDeploy: true
