services:
  - type: web
    name: bronxbot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
