services:
  - type: web
    name: bronxbot-web
    env: python
    buildCommand: pip install -r requirements.web.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: GUNICORN_CMD_ARGS
        value: "--log-level=debug --timeout=120 --keep-alive=65 --workers=2 --threads=4 --worker-class=gthread"
      - key: PYTHONUNBUFFERED
        value: "true"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: MONGO_URI
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_OWNER_ID
        sync: false
      - key: SQLITE_DATABASE_PATH
        value: /data/database.sqlite
    healthCheckPath: /debug
    autoDeploy: true
