name: Discord Notification

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: >
            {
              "embeds": [
                {
                  "title": "🔔 New Commit to Main",
                  "description": "[View Commit](${{ github.event.head_commit.url }})",
                  "color": 3447003,
                  "fields": [
                    {
                      "name": "Author",
                      "value": "${{ github.actor }}"
                    },
                    {
                      "name": "Message",
                      "value": "${{ github.event.head_commit.message }}"
                    }
                  ],
                  "timestamp": "${{ github.event.head_commit.timestamp }}"
                }
              ]
            }
