name: Discord Notification

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only fetch the last commit

      - name: Send Discord Embed via Curl
        run: |
          # Get the raw commit message
          RAW_MESSAGE=$(git log -1 --pretty=%B)
          
          # Escape for JSON and preserve newlines
          ESCAPED_MESSAGE=$(jq -n --arg msg "$RAW_MESSAGE" '$msg' | sed 's/^"//;s/"$//')
          
          PAYLOAD=$(jq -n --arg author "${{ github.actor }}" \
                          --arg author_avatar "${{ github.actor_avatar_url }}" \
                          --arg message "$ESCAPED_MESSAGE" \
                          --arg url "${{ github.event.head_commit.url }}" \
                          --arg timestamp "${{ github.event.head_commit.timestamp }}" \
                          --arg version "${{ secrets.VERSION }}" \
          '{
            "embeds": [
              {
                "description": ("__**New Update**__\nA new update has been released!\n**V" + $version + "**\n" + $message + "\n*[View Full Changelog](" + $url + ")*"),
                "color": 3101622,
                "footer": {
                  "icon_url": $author_avatar,
                  "text": ("Pushed by " + $author)
                },
                "timestamp": $timestamp
              }
            ]
          }')

          curl -X POST -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "${{ secrets.DISCORD_WEBHOOK }}"