name: Discord Notification

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Embed via Curl
        run: |
          # Properly escape newlines and markdown in the commit message
          MESSAGE=$(echo '${{ github.event.head_commit.message }}' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          
          PAYLOAD=$(jq -n --arg author "${{ github.actor }}" \
                          --arg author_avatar "${{ github.actor_avatar_url }}" \
                          --arg message "$MESSAGE" \
                          --arg url "${{ github.event.head_commit.url }}" \
                          --arg timestamp "${{ github.event.head_commit.timestamp }}" \
                          --arg version "${{ secrets.VERSION }}" \
          '{
            "embeds": [
              {
                "id": 120388608,
                "description": ("__**New Update**__\nA new update has been released!\n**V" + $version + "**\n" + $message + "\n*[View Full Changelog](" + $url + ")*"),
                "fields": [],
                "color": 3101622,
                "footer": {
                  "icon_url": $author_avatar,
                  "text": ("Pushed by " + $author)
                },
                "timestamp": $timestamp
              }
            ]
          }')

          curl -X POST -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "${{ secrets.DISCORD_WEBHOOK }}"