name: Discord Notification

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook manually
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [
                {
                  \"title\": \"🔔 New Commit to Main\",
                  \"description\": \"[View Commit](${GITHUB_EVENT_HEAD_COMMIT_URL})\",
                  \"color\": 3447003,
                  \"fields\": [
                    {
                      \"name\": \"Author\",
                      \"value\": \"${GITHUB_ACTOR}\"
                    },
                    {
                      \"name\": \"Message\",
                      \"value\": \"${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}\"
                    }
                  ],
                  \"timestamp\": \"${GITHUB_EVENT_HEAD_COMMIT_TIMESTAMP}\"
                }
              ]
            }" \
            ${{ secrets.DISCORD_WEBHOOK }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_EVENT_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_EVENT_HEAD_COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
          GITHUB_EVENT_HEAD_COMMIT_URL: ${{ github.event.head_commit.url }}
